version: '3.8'

services:
  redis:
    image: 'redis:latest'
    container_name: 'redis-server'
    ports:
      - '6379:6379'
  meteorology-app:
    build: .
    container_name: 'meteorology-app'
    ports:
      - '8080:8080'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379